---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    toolkit.fluxcd.io/tenant: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    toolkit.fluxcd.io/tenant: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-red
  labels:
    toolkit.fluxcd.io/tenant: applications
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-blue
  labels:
    toolkit.fluxcd.io/tenant: applications
