---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  # Original upstream URL:
  # url: https://kubernetes.github.io/ingress-nginx
  # Local ChartMuseum URL:
  url: http://192.168.1.100:8080
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 1h
  # Original upstream URL:
  # url: https://charts.jetstack.io
  # Local ChartMuseum URL:
  url: http://192.168.1.100:8080
